package com.example.demo;

public enum SubCategory {
    REGLIGIOUS_JUDAICA,
    REGLIGIOUS_CHRISTIANITY,
    REGLIGIOUS_BIBLE,

    MATH_ARITHMETIC,
    MATH_GEOMETRY,
    MATH_TRIGONMETRY,
    MATH_CALCULUS,
    MATH_ALGEBRA,

    HISTORY_BRITISH,
    HISTORY_AMERICAN,
    HISTORY_ROMAN,
    HISTORY_MILITARY,

    SCIENCE_CHEMISTRY,
    SCIENCE_ASTRONOMY,
    SCIENCE_PHYSICS,
    SCIENCE_EVOLUTION,
    SCIENCE_NATURAL_HISTORY,

    MEDICAL_HEALTH,
    MEDICAL_DISEASES,
    MEDICAL_OBSTETRICS,
    ;
}
